name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present
        env:
          CI: false
      - run: rm -rf ./node_modules ./.git ./.vscode ./yarn.lock
      - name: Copy folder content recursively to vps
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /home/hypshop/public_html/front
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
